format = """
$username\
$hostname\
$localip\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

right_format = '$all'

[aws]
symbol = 'ï‰° '

[azure]
format = '[$symbol($subscription) ]($style)'

[battery]
disabled = true

[buf]
format = '[$symbol($version )]($style)'
symbol = 'ï’ '

[bun]
format = '[$symbol($version )]($style)'

[c]
format = '[$symbol($version(-$name) )]($style)'
symbol = 'î˜ '

[cmake]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = '[$duration ]($style)'
style = 'bold 8'

[conda]
format = '[$symbol$environment ]($style)'
symbol = 'ï„Œ '

[crystal]
format = '[$symbol($version )]($style)'

[daml]
format = '[$symbol($version )]($style)'

[dart]
format = '[$symbol($version )]($style)'
symbol = 'î˜ '

[deno]
format = '[$symbol($version )]($style)'

[directory]
read_only = ' ï ½'
style = 'bold blue'

[docker_context]
format = '[$symbol$context ]($style)'
symbol = 'ïŒˆ '

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'
symbol = 'î‰µ '

[elm]
format = '[$symbol($version )]($style)'
symbol = 'î˜¬ '

[git_branch]
format = '[$symbol$branch ]($style)'
symbol = 'ï˜ '

[golang]
format = '[$symbol($version )]($style)'
symbol = 'î˜§ '

[haskell]
format = '[$symbol($version )]($style)'
symbol = 'î· '

[hg_branch]
format = '[$symbol$branch ]($style)'
symbol = 'ï˜ '

[java]
format = '[$symbol($version )]($style)'
symbol = 'î‰– '

[julia]
format = '[$symbol($version )]($style)'
symbol = 'î˜¤ '

[kotlin]
format = '[$symbol($version )]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\)) ]($style)'

[line_break]
disabled = true

[lua]
format = '[$symbol($version )]($style)'
symbol = 'î˜  '

[memory_usage]
symbol = 'ï¡š '

[meson]
symbol = 'ï¨¶ '

[nim]
format = '[$symbol($version )]($style)'
symbol = 'ïš¤ '

[nix_shell]
symbol = 'ï‹œ '

[nodejs]
format = '[$symbol($version )]($style)'
symbol = 'îœ˜ '

[package]
format = '[$symbol($version )]($style)'
symbol = 'ï£– '

[perl]
format = '[$symbol($version )]($style)'
symbol = 'î© '

[php]
format = '[$symbol($version )]($style)'
symbol = 'î˜ˆ '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = 'î˜† '

[rlang]
symbol = 'ï³’ '

[ruby]
format = '[$symbol($version )]($style)'
symbol = 'îˆ¾ '

[rust]
format = '[$symbol($version )]($style)'
symbol = 'î¨ '

[scala]
format = '[$symbol($version )]($style)'
symbol = 'îœ· '

[shlvl]
symbol = 'ï„  '

[spack]
symbol = 'ğŸ…¢  '

[swift]
format = '[$symbol($version )]($style)'

[terraform]
format = '[$symbol$workspace ]($style)'
symbol = 'îŒ½  '

[vagrant]
format = '[$symbol($version )]($style)'

[vlang]
format = '[$symbol($version )]($style)'

[zig]
format = '[$symbol($version )]($style)'

